package corinna.network;

import org.jboss.netty.channel.Channel;

import corinna.exception.AdapterException;


public interface IAdapter
{

	public Class<?> CONSTRUCTOR_ARGS[] = { IAdapterConfig.class };

	public boolean isCompatibleWith( Object request, Object response );
	
	public RequestEvent<?,?> translate( Object request, Object response, Channel channel ) 
		throws AdapterException;

	/**
	 * Returns the output response type generated by this adapter.
	 * 
	 * @return
	 */
	public Class<?> getResponseType();

	/**
	 * Returns the output request type generated by this adapter.
	 * @return
	 */
	public Class<?> getRequestType();
	
	public String getName();

	public void onError( RequestEvent<?,?> event, Channel channel, Throwable exception );
	
	public void onSuccess( RequestEvent<?,?> event, Channel channel );

}
